version: '3.8'

services:
  db:
    build:
      context: ../db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: girmiti01

  app:
    build:
      context: ../dop
    ports:
      - "8081:8051"
    depends_on:
      - db
      
