# Use a PostgreSQL base image
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=girmiti01

# Expose the default PostgreSQL port
EXPOSE 5432

# Add volume
VOLUME /var/lib/postgresql/data